name: CI

on: 
  push:
    branch: main
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - users: action/checkout@v3
      - names: Run a one-line script
        run: echo Hello World!!
